### PR TITLE
chore: add commitlint, commitizen, husky

### LINKED ISSUE #33: Add conventional commits
To support cleaner, meaningful commits (and to underline quality efforts), we'll make use of [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). To ensure correct commits before pushing, we'll use [commitlint](https://github.com/conventional-changelog/commitlint). A husky hook can prevent unclean commits. We'll also support creating good commits by offering [commitizen](https://github.com/commitizen/cz-cli).

### PR DESCRIPTION
**Pull request by code-shambles**
resolves #33

### CODE REVIEW

**Comment by n4bb12** [comment]
There shouldn't be a package-lock.json. We're using yarn and yarn.lock.

**Comment by marquesVF** [comment]
Just a dumb question: it was supposed to give me an error if I commit with a random message. Or only when I push it?

Another thing related to what @n4bb12 said: you'd need to run `yarn` so the yarn.lock file is updated as well.

**Comment by n4bb12** [comment]
> Just a dumb question: it was supposed to give me an error or inform me if I commit with an invalid message. Or only when I push it?
> I thought husky would validate my message when I create a commit.
> 
> obs: I didn't use commitizen

Yes but @code-shambles also added a hook. It looks like the hook was named after what it does, but I think it needs to be named according to the git phase. In this case `pre-commit`. See https://github.com/foobaragency/foobar.agency/tree/master/.husky where the hook cancels the commit if code formatting errors.

**Comment by code-shambles** [comment]
> There shouldn't be a package-lock.json. We're using yarn and yarn.lock.

Ok, didn't know that, will remove it. I think I may have taken the npm info from the publish.yml which runs `npm install` 🤔

**Comment by code-shambles** [comment]
> Just a dumb question: it was supposed to give me an error or inform me if I commit with an invalid message. Or only when I push it?
> I thought husky would validate my message when I create a commit.

It worked for me with and without commitizen. I will look into it. @marquesVF did the commit just work normally, although the commit msg was not conventional, or did you see a different error?

> Another thing related to what @n4bb12 said: you'd need to run `yarn` so the yarn.lock file is updated as well.
Ok, thanks!

**Comment by code-shambles** [comment]
> Yes but @code-shambles also added a hook. It looks like the hook was named after what it does, but I think it needs to be named according to the git phase. In this case `pre-commit`.

I followed the [commitlint instructions](https://github.com/conventional-changelog/commitlint#getting-started) quite closely. I simply forgot the `"prepare": "husky install",` line in package.json 🤦 Can you try again @n4bb12 and @marquesVF ?

**Comment by n4bb12** [comment]
Works for me now. What about `cz` / https://github.com/commitizen/cz-cli. Are we expecting this to be installed globally, or should we add it as a dev dependency? What about adding this to the README / CONTRIBUTING guide?

**Comment by code-shambles** [comment]
> Works for me now. What about `cz` / https://github.com/commitizen/cz-cli. Are we expecting this to be installed globally, or should we add it as a dev dependency? What about adding this to the README / CONTRIBUTING guide?

Glad it works. I'm definitely adding notes to the contributing.md that I'm about to create. 

I'd go for a suggestion of global install (or `npx cz`) of commitizen itself for those who want it, because it's more of a helper than an actual requirement. And add [cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) to the dev deps. People who are familiar with conventional commits may still just write their commit messages with -m "chore: and so on" or use the terminal editor of their choice. So we'd just provide the conventional-commits-adapter for those who want to use commitizen.

**Review by n4bb12 — APPROVED** [review]
🏇

**Comment by marquesVF** [comment]
Very good, man! 👍

**Pull request merged**
